server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    database-host: 127.0.0.1
    database-name: shiro
    database-port: 3306
    url: jdbc:mysql://${spring.datasource.database-host}:${spring.datasource.database-port}/${spring.datasource.database-name}?autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&failOverReadOnly=false&rewriteBatchedStatements=true&socketTimeout=30000&connectTimeout=3000&serverTimezone=Asia/Shanghai
    username: root
    password: welcome1
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000
    jedis:
      pool:
        max-idle: 10
        min-idle: 5
        max-active: 100
mybatis:
  mapper-locations: mapper/**/*Mapper.xml
  typeAliasesPackage: com.hytiot.shiro.entity

